language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aliilman/weather-forecast -f Dockerfile.dev .

script:
  - docker run -e CI=true aliilman/weather-forecast yarn test
